#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 𐅱 𐅍 𐅜 𐅙 𐅲 𐆉 𐅺 𐅭 𐅞 𐅠
bspc config border_width         6
bspc config window_gap          22
bspc config top_padding         62
bspc config right_padding       38
bspc config bottom_padding      38
bspc config left_padding        38

bspc config focused_border_color "#5A4E8E"
bspc config normal_border_color "#50487A"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd &
picom --backend glx --config .config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
